spring.application.name=order-inventory-service
spring.data.mongodb.uri=mongodb://localhost:27022/order_inventory_db
spring.data.mongodb.database=order_inventory_db
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
app.api.key=REPLACE_WITH_YOUR_API_KEY
springdoc.swagger-ui.path=/swagger-ui.html
